// swift-tools-version:6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription
import Foundation

let package = Package(
    name: "LibraryTransmission",
    platforms: [.macOS(.v11)],
    products: [
        .library(name: "libtransmission", targets: ["libtransmission"])
    ],
    dependencies: [
        .package(path: "../third-party")
    ],
    targets: [
        .target(
            name: "libtransmission",
            dependencies: [
                .product(name: "crc32c", package: "third-party"),
                .product(name: "dht", package: "third-party"),
                .product(name: "fast_float", package: "third-party"),
                .product(name: "fmt", package: "third-party"),
                .product(name: "b64", package: "third-party"),
                .product(name: "deflate", package: "third-party"),
                .product(name: "eventlib", package: "third-party"),
                .product(name: "natpmp", package: "third-party"),
                .product(name: "psl", package: "third-party"),
                .product(name: "utp", package: "third-party"),
                .product(name: "miniupnpc", package: "third-party"),
                .product(name: "rapidjson", package: "third-party"),
                .product(name: "utfcpp", package: "third-party"),
                .product(name: "sigslot", package: "third-party"),
                .product(name: "small", package: "third-party"),
                .product(name: "wide-integer", package: "third-party"),
                .product(name: "wildmat", package: "third-party"),
            ],
            path: ".",
            sources: [
                "api-compat.cc",
                "announce-list.cc",
                "announcer-http.cc",
                "announcer-udp.cc",
                "announcer.cc",
                "bandwidth.cc",
                "bitfield.cc",
                "block-info.cc",
                "blocklist.cc",
                "cache.cc",
                "clients.cc",
                "completion.cc",
                "crypto-utils-ccrypto.cc",
                "crypto-utils-fallback.cc",
                "crypto-utils.cc",
                "error.cc",
                "file-piece-map.cc",
                "file-posix.cc",
                "file.cc",
                "handshake.cc",
                "inout.cc",
                "ip-cache.cc",
                "log.cc",
                "magnet-metainfo.cc",
                "makemeta.cc",
                "port-forwarding-natpmp.cc",
                "net.cc",
                "open-files.cc",
                "peer-io.cc",
                "peer-mgr-wishlist.cc",
                "peer-mgr.cc",
                "peer-mse.cc",
                "peer-msgs.cc",
                "peer-socket.cc",
                "platform.cc",
                "port-forwarding.cc",
                "quark.cc",
                "resume.cc",
                "rpc-server.cc",
                "rpcimpl.cc",
                "session-id.cc",
                "session.cc",
                "session-alt-speeds.cc",
                "serializer.cc",
                "stats.cc",
                "subprocess-posix.cc",
                "timer-ev.cc",
                "torrent-ctor.cc",
                "torrent-files.cc",
                "torrent-magnet.cc",
                "torrent-metainfo.cc",
                "torrent-queue.cc",
                "torrent.cc",
                "torrents.cc",
                "tr-assert.cc",
                "tr-dht.cc",
                "tr-getopt.cc",
                "tr-lpd.cc",
                "tr-udp.cc",
                "tr-utp.cc",
                "session-thread.cc",
                "utils-ev.cc",
                "port-forwarding-upnp.cc",
                "utils.cc",
                "utils.mm",
                "variant-benc.cc",
                "variant-json.cc",
                "variant.cc",
                "verify.cc",
                "watchdir-generic.cc",
                "watchdir-kqueue.cc",
                "watchdir.cc",
                "web-utils.cc",
                "web.cc",
                "webseed.cc"
            ],
            publicHeadersPath: ".",
            cSettings: [
                .define("WITH_UTP"),
                .define("__TRANSMISSION__"),
                .define("HAVE_FLOCK"),
                .define("WITH_CCRYPTO"),
                .define("WITH_KQUEUE"),
                .define("BUILD_MAC_CLIENT")
            ]
        )
    ],
    cxxLanguageStandard: .cxx20
)
